
GET http://localhost:9999/trainees/5 HTTP/1.1
###

GET http://localhost:9999/trainees/ HTTP/1.1
###

POST http://localhost:9999/trainees/ HTTP/1.1
Content-Type: application/json

{
    "id":"958125",
    "email": "ahishek.r@cts.com",
    "name": "Abhishek R",
    "serviceLine": "ADM"
}
###

POST http://localhost:9999/trainees/ HTTP/1.1
Content-Type: application/json

{
    "email": "ahishek.r",
    "name": "Abhishek R",
    "serviceLine": ""
}
###
DELETE http://localhost:9999/trainees/5 HTTP/1.1
###

PUT http://localhost:9999/trainees/5 HTTP/1.1
Content-Type: application/json

{
    "id": "5",
    "email": "amrita.r",
    "name": "Amrita R K",
    "serviceLine": "CDE"
}
###
